In [12]:
import pandas as pd

df = pd.read_csv("../data/transactions.csv")
df

   transaction_id customer_id   amount      country merchant_category
0            T001        C001     42.5      Germany         Groceries
1            T002        C002    125.0      Germany       Electronics
2            T003        C003     68.2      Germany        Restaurant
3            T004        C004    215.0       France            Travel
4            T005        C005     32.8      Germany         Groceries
5            T006        C006     89.5      Germany        Restaurant
6            T007        C007    145.0  Netherlands       Electronics
7            T008        C008     27.9      Germany         Groceries
8            T009        C009    310.0      Germany            Travel
9            T010        C010     54.3      Germany        Restaurant
10           T011        C001     76.2      Germany         Groceries
11           T012        C002    199.0       France       Electronics
12           T013        C003     45.6      Germany        Restaurant
13           T014        C004    380.0      Germany            Travel
14           T015        C005     22.4      Germany         Groceries
15           T016        C006    115.0  Netherlands        Restaurant
16           T017        C007    260.0      Germany       Electronics
17           T018        C008     38.7      Germany         Groceries
18           T019        C009    175.0       France            Travel
19           T020        C010     61.2      Germany        Restaurant
20           T021        C001     92.0      Germany         Groceries
21           T022        C002    340.0      Germany       Electronics
22           T023        C003     55.8      Germany        Restaurant
23           T024        C004    420.0  Netherlands            Travel
24           T025        C005     19.9      Germany         Groceries
25           T026        C006    130.0      Germany        Restaurant
26           T027        C007    285.0       France       Electronics
27           T028        C008     47.5      Germany         Groceries
28           T029        C009    225.0      Germany            Travel
29           T030        C010     72.8      Germany        Restaurant
30           T031        C001    105.0      Germany         Groceries
31           T032        C002    450.0      Germany       Electronics
32           T033        C003     63.4       France        Restaurant
33           T034        C004    295.0      Germany            Travel
34           T035        C005     35.6      Germany         Groceries
35           T036        C006    155.0      Germany        Restaurant
36           T037        C007    395.0  Netherlands       Electronics
37           T038        C008     51.2      Germany         Groceries
38           T039        C009    240.0      Germany            Travel
39           T040        C010     84.9       France        Restaurant
40           T041        C001    120.0      Germany         Groceries
41           T042        C002    275.0      Germany       Electronics
42           T043        C003     49.3      Germany        Restaurant
43           T044        C004    360.0      Germany            Travel
44           T045        C005     29.8      Germany         Groceries
45           T046        C006   7800.0      Germany       Electronics
46           T047        C007   9200.0       Brazil            Travel
47           T048        C008  15000.0          USA       Electronics
48           T049        C009    110.0      Germany        Restaurant
49           T050        C010    185.0      Germany            Travel

In [13]:
df["amount"].mean()

np.float64(783.51)

In [14]:
df[df["amount"] > 5000]

   transaction_id customer_id   amount  country merchant_category
45           T046        C006   7800.0  Germany       Electronics
46           T047        C007   9200.0   Brazil            Travel
47           T048        C008  15000.0      USA       Electronics

In [15]:
df.describe()

             amount
count     50.000000
mean     783.510000
std     2640.252755
min       19.900000
25%       54.675000
50%      117.500000
75%      271.250000
max    15000.000000

In [16]:
df.groupby("country")["amount"].mean()

country
Brazil          9200.000000
France           170.383333
Germany          338.900000
Netherlands      268.750000
USA            15000.000000
Name: amount, dtype: float64

In [17]:
df = pd.read_csv("../data/transactions.csv")
df

   transaction_id customer_id   amount      country merchant_category
0            T001        C001     42.5      Germany         Groceries
1            T002        C002    125.0      Germany       Electronics
2            T003        C003     68.2      Germany        Restaurant
3            T004        C004    215.0       France            Travel
4            T005        C005     32.8      Germany         Groceries
5            T006        C006     89.5      Germany        Restaurant
6            T007        C007    145.0  Netherlands       Electronics
7            T008        C008     27.9      Germany         Groceries
8            T009        C009    310.0      Germany            Travel
9            T010        C010     54.3      Germany        Restaurant
10           T011        C001     76.2      Germany         Groceries
11           T012        C002    199.0       France       Electronics
12           T013        C003     45.6      Germany        Restaurant
13           T014        C004    380.0      Germany            Travel
14           T015        C005     22.4      Germany         Groceries
15           T016        C006    115.0  Netherlands        Restaurant
16           T017        C007    260.0      Germany       Electronics
17           T018        C008     38.7      Germany         Groceries
18           T019        C009    175.0       France            Travel
19           T020        C010     61.2      Germany        Restaurant
20           T021        C001     92.0      Germany         Groceries
21           T022        C002    340.0      Germany       Electronics
22           T023        C003     55.8      Germany        Restaurant
23           T024        C004    420.0  Netherlands            Travel
24           T025        C005     19.9      Germany         Groceries
25           T026        C006    130.0      Germany        Restaurant
26           T027        C007    285.0       France       Electronics
27           T028        C008     47.5      Germany         Groceries
28           T029        C009    225.0      Germany            Travel
29           T030        C010     72.8      Germany        Restaurant
30           T031        C001    105.0      Germany         Groceries
31           T032        C002    450.0      Germany       Electronics
32           T033        C003     63.4       France        Restaurant
33           T034        C004    295.0      Germany            Travel
34           T035        C005     35.6      Germany         Groceries
35           T036        C006    155.0      Germany        Restaurant
36           T037        C007    395.0  Netherlands       Electronics
37           T038        C008     51.2      Germany         Groceries
38           T039        C009    240.0      Germany            Travel
39           T040        C010     84.9       France        Restaurant
40           T041        C001    120.0      Germany         Groceries
41           T042        C002    275.0      Germany       Electronics
42           T043        C003     49.3      Germany        Restaurant
43           T044        C004    360.0      Germany            Travel
44           T045        C005     29.8      Germany         Groceries
45           T046        C006   7800.0      Germany       Electronics
46           T047        C007   9200.0       Brazil            Travel
47           T048        C008  15000.0          USA       Electronics
48           T049        C009    110.0      Germany        Restaurant
49           T050        C010    185.0      Germany            Travel

In [18]:
df.sort_values("amount", ascending=False)

   transaction_id customer_id   amount      country merchant_category
47           T048        C008  15000.0          USA       Electronics
46           T047        C007   9200.0       Brazil            Travel
45           T046        C006   7800.0      Germany       Electronics
31           T032        C002    450.0      Germany       Electronics
23           T024        C004    420.0  Netherlands            Travel
36           T037        C007    395.0  Netherlands       Electronics
13           T014        C004    380.0      Germany            Travel
43           T044        C004    360.0      Germany            Travel
21           T022        C002    340.0      Germany       Electronics
8            T009        C009    310.0      Germany            Travel
33           T034        C004    295.0      Germany            Travel
26           T027        C007    285.0       France       Electronics
41           T042        C002    275.0      Germany       Electronics
16           T017        C007    260.0      Germany       Electronics
38           T039        C009    240.0      Germany            Travel
28           T029        C009    225.0      Germany            Travel
3            T004        C004    215.0       France            Travel
11           T012        C002    199.0       France       Electronics
49           T050        C010    185.0      Germany            Travel
18           T019        C009    175.0       France            Travel
35           T036        C006    155.0      Germany        Restaurant
6            T007        C007    145.0  Netherlands       Electronics
25           T026        C006    130.0      Germany        Restaurant
1            T002        C002    125.0      Germany       Electronics
40           T041        C001    120.0      Germany         Groceries
15           T016        C006    115.0  Netherlands        Restaurant
48           T049        C009    110.0      Germany        Restaurant
30           T031        C001    105.0      Germany         Groceries
20           T021        C001     92.0      Germany         Groceries
5            T006        C006     89.5      Germany        Restaurant
39           T040        C010     84.9       France        Restaurant
10           T011        C001     76.2      Germany         Groceries
29           T030        C010     72.8      Germany        Restaurant
2            T003        C003     68.2      Germany        Restaurant
32           T033        C003     63.4       France        Restaurant
19           T020        C010     61.2      Germany        Restaurant
22           T023        C003     55.8      Germany        Restaurant
9            T010        C010     54.3      Germany        Restaurant
37           T038        C008     51.2      Germany         Groceries
42           T043        C003     49.3      Germany        Restaurant
27           T028        C008     47.5      Germany         Groceries
12           T013        C003     45.6      Germany        Restaurant
0            T001        C001     42.5      Germany         Groceries
17           T018        C008     38.7      Germany         Groceries
34           T035        C005     35.6      Germany         Groceries
4            T005        C005     32.8      Germany         Groceries
44           T045        C005     29.8      Germany         Groceries
7            T008        C008     27.9      Germany         Groceries
14           T015        C005     22.4      Germany         Groceries
24           T025        C005     19.9      Germany         Groceries

In [19]:
df["amount"].describe()

count       50.000000
mean       783.510000
std       2640.252755
min         19.900000
25%         54.675000
50%        117.500000
75%        271.250000
max      15000.000000
Name: amount, dtype: float64

In [20]:
q1 = df["amount"].quantile(0.25)
q3 = df["amount"].quantile(0.75)

iqr = q3 - q1

q1, q3, iqr

(np.float64(54.675), np.float64(271.25), np.float64(216.575))

In [21]:
upper_threshold = q3 + 1.5 * iqr
upper_threshold

np.float64(596.1125)

In [22]:
df[df["amount"] > upper_threshold]

   transaction_id customer_id   amount  country merchant_category
45           T046        C006   7800.0  Germany       Electronics
46           T047        C007   9200.0   Brazil            Travel
47           T048        C008  15000.0      USA       Electronics

In [ ]:
## Isolation Forest

In [23]:
from sklearn.ensemble import IsolationForest

model = IsolationForest(
    contamination=0.06,
    random_state=42,
)

df["ml_prediction"] = model.fit_predict(df[["amount"]])

df[["transaction_id", "amount", "ml_prediction"]]

   transaction_id   amount  ml_prediction
0            T001     42.5              1
1            T002    125.0              1
2            T003     68.2              1
3            T004    215.0              1
4            T005     32.8              1
5            T006     89.5              1
6            T007    145.0              1
7            T008     27.9              1
8            T009    310.0              1
9            T010     54.3              1
10           T011     76.2              1
11           T012    199.0              1
12           T013     45.6              1
13           T014    380.0              1
14           T015     22.4              1
15           T016    115.0              1
16           T017    260.0              1
17           T018     38.7              1
18           T019    175.0              1
19           T020     61.2              1
20           T021     92.0              1
21           T022    340.0              1
22           T023     55.8              1
23           T024    420.0              1
24           T025     19.9              1
25           T026    130.0              1
26           T027    285.0              1
27           T028     47.5              1
28           T029    225.0              1
29           T030     72.8              1
30           T031    105.0              1
31           T032    450.0              1
32           T033     63.4              1
33           T034    295.0              1
34           T035     35.6              1
35           T036    155.0              1
36           T037    395.0              1
37           T038     51.2              1
38           T039    240.0              1
39           T040     84.9              1
40           T041    120.0              1
41           T042    275.0              1
42           T043     49.3              1
43           T044    360.0              1
44           T045     29.8              1
45           T046   7800.0             -1
46           T047   9200.0             -1
47           T048  15000.0             -1
48           T049    110.0              1
49           T050    185.0              1